# -*- coding: utf-8 -*-
"""rca_chart7_discrepancy_now_resolved.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14LdtAOi8Ciqip26KRExZJCtAw-PJCGvE

Project ID: driiiportfolio
Dataset Name: meta_music
---
**Table Names:**

driiiportfolio.meta_music.dim_metadata_anomalies

driiiportfolio.meta_music.dim_music_catalog

driiiportfolio.meta_music.dim_suppliers

driiiportfolio.meta_music.fct_ingestion_log
"""

BQ_PROJECT = 'driiiportfolio'
print(f"BigQuery Project ID: {BQ_PROJECT}")

import pandas as pd
import pandas_gbq
from IPython.display import display

# Extract the SQL query from the markdown cell
# In a real scenario, this would be a more robust way to get cell content.
# For now, let's manually copy the query for execution.
sql_query = """
CREATE OR REPLACE VIEW `driiiportfolio.meta_music.v_spatial_audio_readiness_audit` AS
/**
 * SANITIZED Optimized Spatial Audio Audit View
 */
SELECT
    a.issue_id,
    a.severity AS technical_severity,
    c.track_id,
    c.isrc,
    c.title,
    c.ddex_version,
    c.is_spatial_ready,
    a.detected_timestamp
FROM `driiiportfolio.meta_music.dim_metadata_anomalies` a
JOIN `driiiportfolio.meta_music.dim_music_catalog` c
  -- TRIM and LOWER handle hidden CSV artifacts
  ON TRIM(LOWER(a.track_id)) = TRIM(LOWER(c.track_id))
WHERE a.issue_code = 'SPATIAL_VERSION_MISMATCH'
ORDER BY a.severity ASC;
"""

# The original query is for creating a VIEW. To debug, we need to run the SELECT statement.
# Remove CREATE OR REPLACE VIEW and everything before the SELECT.
select_query_start_index = sql_query.find("SELECT")
if select_query_start_index != -1:
    executable_query = sql_query[select_query_start_index:].replace("```SQL", "").replace("```", "").strip()
else:
    executable_query = ""
    print("Could not find a SELECT statement in the provided SQL.")

if executable_query:
    print("Executing query:")
    print(executable_query)
    try:
        df_result = pandas_gbq.read_gbq(executable_query, project_id=BQ_PROJECT)
        if not df_result.empty:
            print("Query executed successfully. Displaying first 5 rows:")
            display(df_result.head())
        else:
            print("Query executed successfully, but returned no data. This means the conditions in the WHERE clause might not be met, or there's no matching data across the join.")
    except Exception as e:
        print(f"An error occurred during query execution: {e}")
else:
    print("No executable query to run.")

"""### Debugging the Empty View: Checking `dim_metadata_anomalies`

First, let's examine the `dim_metadata_anomalies` table to see if any records match the `issue_code = 'SPATIAL_VERSION_MISMATCH'` condition in the original query. We'll check all unique `issue_code` values and their counts.
"""

query_anomalies_issue_codes = f"""
SELECT
    issue_code,
    COUNT(*) as count
FROM `{BQ_PROJECT}.meta_music.dim_metadata_anomalies`
GROUP BY issue_code
ORDER BY count DESC
"""

print("Executing query to check issue codes in dim_metadata_anomalies:")
df_anomalies_codes = pandas_gbq.read_gbq(query_anomalies_issue_codes, project_id=BQ_PROJECT)

if not df_anomalies_codes.empty:
    display(df_anomalies_codes)
else:
    print("No issue codes found in dim_metadata_anomalies. The table might be empty or inaccessible.")

"""### Debugging the Empty View: Isolating the JOIN Condition

Since `df_anomalies_codes` confirms that `SPATIAL_VERSION_MISMATCH` exists, the issue might be with the `JOIN` condition between `dim_metadata_anomalies` and `dim_music_catalog`. Let's execute the core `SELECT` statement without the `WHERE` clause to see if the join itself produces any results.
"""

query_without_where = f"""
SELECT
    a.issue_id,
    a.severity AS technical_severity,
    c.track_id,
    c.isrc,
    c.title,
    c.ddex_version,
    c.is_spatial_ready,
    a.detected_timestamp
FROM `{BQ_PROJECT}.meta_music.dim_metadata_anomalies` a
JOIN `{BQ_PROJECT}.meta_music.dim_music_catalog` c
  ON TRIM(LOWER(a.track_id)) = TRIM(LOWER(c.track_id))
LIMIT 100 -- Limit to a small number of rows for debugging purposes
"""

print("Executing query without the WHERE clause (limited to 100 rows):")
try:
    df_join_check = pandas_gbq.read_gbq(query_without_where, project_id=BQ_PROJECT)
    if not df_join_check.empty:
        print(f"Join produced {len(df_join_check)} records. Displaying first 5 rows:")
        display(df_join_check.head())
        # If join works, the issue is likely with the 'SPATIAL_VERSION_MISMATCH' condition not matching any joined records.
        # This might indicate that records with 'SPATIAL_VERSION_MISMATCH' simply do not have a corresponding track_id in dim_music_catalog.
    else:
        print("The JOIN itself produced no results. This means there are no matching track_id values between dim_metadata_anomalies and dim_music_catalog, even after TRIM(LOWER()).")
        print("We need to investigate the track_id values in both tables.")
except Exception as e:
    print(f"An error occurred during query execution: {e}")

"""### Investigating `track_id`s in `dim_metadata_anomalies`

Given that the join produced no results, let's look at a sample of `track_id` values from the `dim_metadata_anomalies` table, specifically for records where `issue_code = 'SPATIAL_VERSION_MISMATCH'`. This will help us understand the format and content of these IDs.
"""

query_anomalies_track_ids = f"""
SELECT DISTINCT
    track_id
FROM `{BQ_PROJECT}.meta_music.dim_metadata_anomalies`
WHERE issue_code = 'SPATIAL_VERSION_MISMATCH'
LIMIT 20
"""

print("Executing query to sample track_ids from dim_metadata_anomalies (SPATIAL_VERSION_MISMATCH):")
try:
    df_anomalies_track_ids = pandas_gbq.read_gbq(query_anomalies_track_ids, project_id=BQ_PROJECT)
    if not df_anomalies_track_ids.empty:
        print(f"Found {len(df_anomalies_track_ids)} unique track_ids. Displaying all:")
        display(df_anomalies_track_ids)
    else:
        print("No track_ids found for 'SPATIAL_VERSION_MISMATCH' in dim_metadata_anomalies. This contradicts previous findings, indicating a potential issue with the `DISTINCT` clause or data access.")
except Exception as e:
    print(f"An error occurred during query execution: {e}")

"""### Investigating `track_id`s in `dim_music_catalog`

Now that we have a sample of `track_id`s from `dim_metadata_anomalies` (specifically for `SPATIAL_VERSION_MISMATCH`), let's check if any of these IDs exist in the `dim_music_catalog` table. This will help us understand why the join previously returned no results.
"""

# Extract the track_ids from the previous result for use in the next query
anomalies_track_ids_list = df_anomalies_track_ids['track_id'].tolist()
anomalies_track_ids_str = ', '.join([f"'{tid}'" for tid in anomalies_track_ids_list])

query_catalog_track_ids = f"""
SELECT DISTINCT
    track_id,
    isrc,
    title
FROM `{BQ_PROJECT}.meta_music.dim_music_catalog`
WHERE TRIM(LOWER(track_id)) IN ({anomalies_track_ids_str})
LIMIT 20
"""

print("Executing query to check for matching track_ids in dim_music_catalog:")
try:
    df_catalog_track_ids = pandas_gbq.read_gbq(query_catalog_track_ids, project_id=BQ_PROJECT)
    if not df_catalog_track_ids.empty:
        print(f"Found {len(df_catalog_track_ids)} matching track_ids in dim_music_catalog. Displaying all:")
        display(df_catalog_track_ids)
    else:
        print("No matching track_ids found in dim_music_catalog for the sampled anomalies. This confirms that the track_ids from anomalies with 'SPATIAL_VERSION_MISMATCH' do not exist in the music catalog, even with TRIM(LOWER()).")
        print("This is the root cause of the empty view. The `track_id` values used in `dim_metadata_anomalies` for 'SPATIAL_VERSION_MISMATCH' do not link to any existing `track_id`s in `dim_music_catalog`.")
        print("We need to investigate why these specific anomaly track_ids are not present in the catalog.")
except Exception as e:
    print(f"An error occurred during query execution: {e}")

"""```SQL
CREATE OR REPLACE VIEW `driiiportfolio.meta_music.v_spatial_audio_readiness_audit` AS
/**
 * SANITIZED Optimized Spatial Audio Audit View
 */
SELECT
    a.issue_id,
    a.severity AS technical_severity,
    c.track_id,
    c.isrc,
    c.title,
    c.ddex_version,
    c.is_spatial_ready,
    a.detected_timestamp
FROM `driiiportfolio.meta_music.dim_metadata_anomalies` a
JOIN `driiiportfolio.meta_music.dim_music_catalog` c
  -- TRIM and LOWER handle hidden CSV artifacts
  ON TRIM(LOWER(a.track_id)) = TRIM(LOWER(c.track_id))
WHERE a.issue_code = 'SPATIAL_VERSION_MISMATCH'
ORDER BY a.severity ASC;
```

### Investigating `isrc` as an Alternative Join Key

Given that `track_id` did not produce any matches between `dim_metadata_anomalies` and `dim_music_catalog` for 'SPATIAL_VERSION_MISMATCH' records, let's explore `isrc` as a potential alternative join key.

First, we'll examine the columns available in `dim_metadata_anomalies` to see if `isrc` is present and if it contains data for our relevant anomalies.
"""

print("Checking columns of dim_metadata_anomalies:")
query_anomalies_cols = f"""
SELECT * FROM `{BQ_PROJECT}.meta_music.dim_metadata_anomalies` LIMIT 1
"""
df_anomalies_schema = pandas_gbq.read_gbq(query_anomalies_cols, project_id=BQ_PROJECT)
print(df_anomalies_schema.columns.tolist())

if 'isrc' in df_anomalies_schema.columns:
    print("\nSampling 'isrc' values from dim_metadata_anomalies for 'SPATIAL_VERSION_MISMATCH':")
    query_anomalies_isrc = f"""
    SELECT DISTINCT
        isrc
    FROM `{BQ_PROJECT}.meta_music.dim_metadata_anomalies`
    WHERE issue_code = 'SPATIAL_VERSION_MISMATCH'
    AND isrc IS NOT NULL
    LIMIT 20
    """
    df_anomalies_isrc_sample = pandas_gbq.read_gbq(query_anomalies_isrc, project_id=BQ_PROJECT)
    if not df_anomalies_isrc_sample.empty:
        display(df_anomalies_isrc_sample)
        anomalies_isrc_list = df_anomalies_isrc_sample['isrc'].tolist()
    else:
        print("No 'isrc' values found in dim_metadata_anomalies for 'SPATIAL_VERSION_MISMATCH'.")
        anomalies_isrc_list = []
else:
    print("\n'isrc' column not found in dim_metadata_anomalies. Cannot use it as a join key.")
    anomalies_isrc_list = []

"""Now, let's check the `dim_music_catalog` table for the `isrc` column and try to find matching `isrc` values from our anomalies sample."""

print("Checking columns of dim_music_catalog:")
query_catalog_cols = f"""
SELECT * FROM `{BQ_PROJECT}.meta_music.dim_music_catalog` LIMIT 1
"""
df_catalog_schema = pandas_gbq.read_gbq(query_catalog_cols, project_id=BQ_PROJECT)
print(df_catalog_schema.columns.tolist())

if 'isrc' in df_catalog_schema.columns:
    if anomalies_isrc_list:
        print("\nChecking for matching 'isrc' values in dim_music_catalog:")
        anomalies_isrc_str = ', '.join([f"'{tid}'" for tid in anomalies_isrc_list])
        query_catalog_matching_isrc = f"""
        SELECT DISTINCT
            track_id,
            isrc,
            title
        FROM `{BQ_PROJECT}.meta_music.dim_music_catalog`
        WHERE TRIM(LOWER(isrc)) IN ({anomalies_isrc_str})
        LIMIT 20
        """
        df_catalog_matching_isrc = pandas_gbq.read_gbq(query_catalog_matching_isrc, project_id=BQ_PROJECT)
        if not df_catalog_matching_isrc.empty:
            print(f"Found {len(df_catalog_matching_isrc)} matching ISRC values in dim_music_catalog. Displaying all:")
            display(df_catalog_matching_isrc)
            print("\nIt appears 'isrc' could be a viable join key. Let's try to update the view definition using 'isrc'.")
            # Proceed to modifying the view if this is successful
        else:
            print("No matching 'isrc' values found in dim_music_catalog for the sampled anomalies, even with TRIM(LOWER()).")
            print("This indicates that 'isrc' is also not a suitable direct join key or the data is inconsistent.")
    else:
        print("No 'isrc' values to check from anomalies table.")
else:
    print("\n'isrc' column not found in dim_music_catalog. Cannot use it as a join key.")

"""# PAGE TITLE: Catalog Integrity & Technical Compliance

## CHART 7: Spatial Audio Discrepancy Detail

### 1. Chart Setup (Setup Tab Configuration)

- **Chart Type:** Table

- **Data Source:** `driiiportfolio.meta_music.v_spatial_audio_readiness_audit`

> (Note: Ensure this view is connected, as it performs the JOIN between the anomalies and the catalog).

#### Dimensions:

- `technical_severity` *(Set as primary dimension)*
- `issue_id`
- `isrc`
- `title`
- `ddex_version`

#### Metric(s):

- `Record Count` *(renamed to Anomalies)*

#### Sorting:

- **Field:** `technical_severity`
- **Order:** Ascending

> (This ensures `P0 - HIGH` records appear at the top of the list).

#### Number of Rows:

- Set to `50` *(with pagination enabled).*

---

### 2. Calculated Fields

No field-level calculation required in Looker Studio.

#### Rationale:

The severity logic is now "Hardcoded" into the `qc_job.py` and stored in BigQuery. This improves dashboard performance and ensures "Single Source of Truth" across the entire pipeline.

---

### 3. Visualization & Style Configuration (Style Tab)

#### Table Header:

- Show header
- Wrap text

#### Conditional Formatting (Critical for Triage):

##### Rule 1:

If `technical_severity` Equal to `P0 - HIGH`

- **Style:** Background: Light Red | Font: Dark Red | Apply to: Entire Row.

##### Rule 2:

If `technical_severity` Equal to `P1 - MEDIUM`

- **Style:** Background: Light Orange | Font: Dark Orange | Apply to: Entire Row.

#### Table Body:

- Show row numbers.
- Cell border color: Light Grey.

#### Chart Interactions:

- Enable Cross-filtering.

> (Clicking a Severity level should filter any other charts on the page to that specific risk category).

---

### 4. Page-Level Controls (New)

#### Control Type:

- Drop-down List

#### Control Field:

- `technical_severity`

#### Label:

- "Filter by Priority Level"

#### Placement:

- Directly above Chart 7.

---

## FINAL OUTPUT FORMAT (STRICT)

# PAGE TITLE: Catalog Integrity & Technical Compliance

## CHART 7: Spatial Audio Discrepancy Detail

- **Chart Type:** Table
- **Data Source:** `driiiportfolio.meta_music.v_spatial_audio_readiness_audit`
- **Dimensions:** `technical_severity`, `issue_id`, `isrc`, `title`, `ddex_version`
- **Metrics:** `Record Count` *(as Anomalies)*
- **Drill-Down:** N/A
- **Breakdown Dimension:** N/A
- **Date Range Settings:** `detected_timestamp`
"""

import pandas as pd
import uuid
from datetime import datetime

# 1. Load the ACTIVE catalog (The Source of Truth)
# Corrected path: removed 'data/' since the file is in the root content directory
catalog_df = pd.read_csv('dim_music_catalog.csv')

print(f"Analyzing {len(catalog_df)} catalog tracks for spatial discrepancies...")

# 2. Identify the specific 6,950 tracks failing compliance
# We use the exact logic from your analysis
mask = (catalog_df['is_spatial_ready'] == True) & (catalog_df['ddex_version'] != 'ERN 4.3')
valid_anomalies = catalog_df[mask].copy()

# 3. Build the Anomalies table USING IDs that definitely exist in the catalog
anomalies_df = pd.DataFrame({
    'issue_id': [f"ISS_QC_{uuid.uuid4().hex[:8].upper()}" for _ in range(len(valid_anomalies))],
    'track_id': valid_anomalies['track_id'].values, # Direct mapping
    'issue_code': 'SPATIAL_VERSION_MISMATCH',
    'severity': valid_anomalies['ddex_version'].map({
        'ERN 3.8': 'P0 - HIGH',
        'ERN 4.2': 'P1 - MEDIUM'
    }).fillna('P2 - LOW'),
    'detected_timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
})

# 4. Export the healed file
# Corrected path: removed 'data/' to save in the root content directory
anomalies_df.to_csv('dim_metadata_anomalies.csv', index=False)
print(f"SUCCESS: Generated {len(anomalies_df)} anomalies with 100% referential integrity.")

"""### Uploading New `dim_metadata_anomalies.csv` to BigQuery and Verifying the View

Now that we have a corrected `dim_metadata_anomalies.csv` file with referential integrity, we need to upload it to BigQuery to update the `driiiportfolio.meta_music.dim_metadata_anomalies` table. After the upload, we will recreate the view and check if it now contains data.

**Action Required:**

1.  **Upload the `dim_metadata_anomalies.csv` file:**
    *   Go to your BigQuery console.
    *   Navigate to your `driiiportfolio.meta_music` dataset.
    *   Find the `dim_metadata_anomalies` table.
    *   Click on 'Details' -> 'Upload' or 'Load data' and select the `dim_metadata_anomalies.csv` file from your local machine.  **Crucially, ensure you select 'Overwrite table' as the write disposition.**

Once the upload is successful, execute the following cell to recreate the view and confirm the data.
"""

print("Attempting to recreate the view and fetch data after CSV upload...")

# The original SQL query to create the view
sql_create_view = """
CREATE OR REPLACE VIEW `driiiportfolio.meta_music.v_spatial_audio_readiness_audit` AS
/**
 * SANITIZED Optimized Spatial Audio Audit View
 */
SELECT
    a.issue_id,
    a.severity AS technical_severity,
    c.track_id,
    c.isrc,
    c.title,
    c.ddex_version,
    c.is_spatial_ready,
    a.detected_timestamp
FROM `driiiportfolio.meta_music.dim_metadata_anomalies` a
JOIN `driiiportfolio.meta_music.dim_music_catalog` c
  ON TRIM(LOWER(a.track_id)) = TRIM(LOWER(c.track_id))
WHERE a.issue_code = 'SPATIAL_VERSION_MISMATCH'
ORDER BY a.severity ASC;
"""

# Execute the CREATE OR REPLACE VIEW statement
try:
    pandas_gbq.read_gbq(sql_create_view, project_id=BQ_PROJECT, dialect='standard')
    print("View 'v_spatial_audio_readiness_audit' successfully recreated in BigQuery.")
except Exception as e:
    print(f"Error recreating view: {e}")

# Now, let's query the view to see if it has data
query_view_data = f"""
SELECT * FROM `driiiportfolio.meta_music.v_spatial_audio_readiness_audit` LIMIT 10
"""

try:
    df_view_data = pandas_gbq.read_gbq(query_view_data, project_id=BQ_PROJECT)
    if not df_view_data.empty:
        print("\nView now contains data! Displaying first 10 rows:")
        display(df_view_data)
        print("The `v_spatial_audio_readiness_audit` view is now correctly populated and ready for use in Looker Studio.")
    else:
        print("\nThe view is still empty. Please double-check that the `dim_metadata_anomalies.csv` file was uploaded correctly and overwrote the existing table in BigQuery.")
except Exception as e:
    print(f"Error querying view: {e}")

"""### Verify `dim_metadata_anomalies` table content in BigQuery

This step will directly query the `dim_metadata_anomalies` table in BigQuery to confirm if the newly generated data (specifically for `SPATIAL_VERSION_MISMATCH`) is present after the manual upload.
"""

print("Querying `dim_metadata_anomalies` directly to verify contents...")

query_anomalies_content = f"""
SELECT
    issue_id,
    track_id,
    issue_code,
    severity,
    detected_timestamp
FROM `{BQ_PROJECT}.meta_music.dim_metadata_anomalies`
WHERE issue_code = 'SPATIAL_VERSION_MISMATCH'
LIMIT 10
"""

try:
    df_anomalies_bq = pandas_gbq.read_gbq(query_anomalies_content, project_id=BQ_PROJECT)
    if not df_anomalies_bq.empty:
        print("\n`dim_metadata_anomalies` in BigQuery now contains 'SPATIAL_VERSION_MISMATCH' data:")
        display(df_anomalies_bq)
        print("Since the base table now has the data, the view should also populate. Please re-run the previous cell (cell 0db64349) to recreate and check the view again.")
    else:
        print("\n`dim_metadata_anomalies` table in BigQuery still does NOT contain 'SPATIAL_VERSION_MISMATCH' data. The manual upload/overwrite step was likely not successful.")
        print("Please re-attempt the manual upload of `dim_metadata_anomalies.csv` to BigQuery, ensuring you **overwrite** the existing table.")
except Exception as e:
    print(f"An error occurred while querying dim_metadata_anomalies: {e}")

"""### Directly Uploading `anomalies_df` to BigQuery

To ensure the BigQuery table `dim_metadata_anomalies` is correctly updated with the data we generated, we will directly upload the `anomalies_df` DataFrame. This will overwrite the existing table with the new, referentially-sound anomaly data.
"""

print("Uploading anomalies_df directly to BigQuery table: `driiiportfolio.meta_music.dim_metadata_anomalies`...")

try:
    # Upload the DataFrame to BigQuery, overwriting the table
    anomalies_df.to_gbq(
        destination_table='meta_music.dim_metadata_anomalies',
        project_id=BQ_PROJECT,
        if_exists='replace', # Crucial: ensures the old data is replaced
        progress_bar=True
    )
    print("Successfully uploaded anomalies_df to BigQuery.")
except Exception as e:
    print(f"Error uploading to BigQuery: {e}")

"""### Recreate and Query the View

Now that the `dim_metadata_anomalies` table in BigQuery is confirmed to be updated, let's re-run the process to recreate the view and query it. It should now be populated.
"""

print("Attempting to recreate the view and fetch data after direct BigQuery upload...")

# The original SQL query to create the view
sql_create_view = """
CREATE OR REPLACE VIEW `driiiportfolio.meta_music.v_spatial_audio_readiness_audit` AS
/**
 * SANITIZED Optimized Spatial Audio Audit View
 */
SELECT
    a.issue_id,
    a.severity AS technical_severity,
    c.track_id,
    c.isrc,
    c.title,
    c.ddex_version,
    c.is_spatial_ready,
    a.detected_timestamp
FROM `driiiportfolio.meta_music.dim_metadata_anomalies` a
JOIN `driiiportfolio.meta_music.dim_music_catalog` c
  ON TRIM(LOWER(a.track_id)) = TRIM(LOWER(c.track_id))
WHERE a.issue_code = 'SPATIAL_VERSION_MISMATCH'
ORDER BY a.severity ASC;
"""

# Execute the CREATE OR REPLACE VIEW statement
try:
    pandas_gbq.read_gbq(sql_create_view, project_id=BQ_PROJECT, dialect='standard')
    print("View 'v_spatial_audio_readiness_audit' successfully recreated in BigQuery.")
except Exception as e:
    print(f"Error recreating view: {e}")

# Now, let's query the view to see if it has data
query_view_data = f"""
SELECT * FROM `driiiportfolio.meta_music.v_spatial_audio_readiness_audit` LIMIT 10
"""

try:
    df_view_data = pandas_gbq.read_gbq(query_view_data, project_id=BQ_PROJECT)
    if not df_view_data.empty:
        print("\nView now contains data! Displaying first 10 rows:")
        display(df_view_data)
        print("The `v_spatial_audio_readiness_audit` view is now correctly populated and ready for use in Looker Studio.")
    else:
        print("\nThe view is still empty. This is unexpected after direct upload. Please check BigQuery table content manually.")
except Exception as e:
    print(f"Error querying view: {e}")

"""### Final Verification of `track_id` Join Across BigQuery Tables

Despite `dim_metadata_anomalies` being populated and the view recreated, the view remains empty. This section performs a direct check to ensure that `track_id` values from the *newly populated* `dim_metadata_anomalies` table indeed have matches in `dim_music_catalog` within BigQuery.
"""

print("Fetching sample track_ids from the *current* `dim_metadata_anomalies` in BigQuery...")
query_anomalies_bq_sample_track_ids = f"""
SELECT DISTINCT
    track_id
FROM `{BQ_PROJECT}.meta_music.dim_metadata_anomalies`
WHERE issue_code = 'SPATIAL_VERSION_MISMATCH'
LIMIT 20
"""
try:
    df_anomalies_bq_sample = pandas_gbq.read_gbq(query_anomalies_bq_sample_track_ids, project_id=BQ_PROJECT)
    if not df_anomalies_bq_sample.empty:
        current_anomalies_track_ids = df_anomalies_bq_sample['track_id'].tolist()
        current_anomalies_track_ids_str = ', '.join([f"'{tid}'" for tid in current_anomalies_track_ids])
        print(f"Sample track_ids from dim_metadata_anomalies: {current_anomalies_track_ids}")

        print("\nChecking if these track_ids exist in `dim_music_catalog` in BigQuery...")
        query_catalog_matching_current_ids = f"""
        SELECT DISTINCT
            track_id,
            isrc,
            title
        FROM `{BQ_PROJECT}.meta_music.dim_music_catalog`
        WHERE TRIM(LOWER(track_id)) IN ({current_anomalies_track_ids_str})
        LIMIT 20
        """
        df_catalog_matches = pandas_gbq.read_gbq(query_catalog_matching_current_ids, project_id=BQ_PROJECT)

        if not df_catalog_matches.empty:
            print(f"Found {len(df_catalog_matches)} matching track_ids in `dim_music_catalog`! Displaying matches:")
            display(df_catalog_matches)
            print("This is highly unusual. The `dim_metadata_anomalies` table contains the data, `dim_music_catalog` contains matching track_ids, and the view was recreated. If the view is still empty, there might be a very subtle data type or character encoding issue, or a temporary BigQuery service inconsistency. Let's try recreating and querying the view one last time to be sure.")

            # Re-run the view creation and query
            print("\nAttempting to recreate the view and fetch data one final time...")
            sql_create_view = """
            CREATE OR REPLACE VIEW `driiiportfolio.meta_music.v_spatial_audio_readiness_audit` AS
            /**
             * SANITIZED Optimized Spatial Audio Audit View
             */
            SELECT
                a.issue_id,
                a.severity AS technical_severity,
                c.track_id,
                c.isrc,
                c.title,
                c.ddex_version,
                c.is_spatial_ready,
                a.detected_timestamp
            FROM `driiiportfolio.meta_music.dim_metadata_anomalies` a
            JOIN `driiiportfolio.meta_music.dim_music_catalog` c
              ON TRIM(LOWER(a.track_id)) = TRIM(LOWER(c.track_id))
            WHERE a.issue_code = 'SPATIAL_VERSION_MISMATCH'
            ORDER BY a.severity ASC;
            """
            pandas_gbq.read_gbq(sql_create_view, project_id=BQ_PROJECT, dialect='standard')
            print("View 'v_spatial_audio_readiness_audit' successfully recreated in BigQuery.")

            query_view_data = f"""
            SELECT * FROM `driiiportfolio.meta_music.v_spatial_audio_readiness_audit` LIMIT 10
            """
            df_view_data = pandas_gbq.read_gbq(query_view_data, project_id=BQ_PROJECT)
            if not df_view_data.empty:
                print("\nSUCCESS! View now contains data! Displaying first 10 rows:")
                display(df_view_data)
                print("The `v_spatial_audio_readiness_audit` view is now correctly populated and ready for use in Looker Studio.")
            else:
                print("\nThe view is *still* empty. This is unexpected. At this point, the issue is very likely beyond typical data discrepancies and may require direct inspection of BigQuery table schemas, data types, or a BigQuery support ticket.")

        else:
            print("No matching track_ids found in `dim_music_catalog` for the current anomalies. This implies the `dim_music_catalog` table either doesn't have these track_ids, or there's a problem with the `TRIM(LOWER())` function on these specific values in `dim_music_catalog`.")

    else:
        print("No 'SPATIAL_VERSION_MISMATCH' records found in `dim_metadata_anomalies` even after direct upload. This indicates the upload might have failed or been corrupted.")

except Exception as e:
    print(f"An error occurred during final verification: {e}")

"""### Final Step: Recreating and Querying the View After Catalog Update

Now that both `dim_metadata_anomalies` and `dim_music_catalog` are confirmed (or assumed, after the manual upload) to contain synchronized and referentially sound data in BigQuery, let's re-run the view creation and query. This should now successfully populate the view.
"""

print("Attempting to recreate the view and fetch data after updating `dim_music_catalog`...")

# The original SQL query to create the view
sql_create_view = """
CREATE OR REPLACE VIEW `driiiportfolio.meta_music.v_spatial_audio_readiness_audit` AS
/**
 * SANITIZED Optimized Spatial Audio Audit View
 */
SELECT
    a.issue_id,
    a.severity AS technical_severity,
    c.track_id,
    c.isrc,
    c.title,
    c.ddex_version,
    c.is_spatial_ready,
    a.detected_timestamp
FROM `driiiportfolio.meta_music.dim_metadata_anomalies` a
JOIN `driiiportfolio.meta_music.dim_music_catalog` c
  ON TRIM(LOWER(a.track_id)) = TRIM(LOWER(c.track_id))
WHERE a.issue_code = 'SPATIAL_VERSION_MISMATCH'
ORDER BY a.severity ASC;
"""

# Execute the CREATE OR REPLACE VIEW statement
try:
    pandas_gbq.read_gbq(sql_create_view, project_id=BQ_PROJECT, dialect='standard')
    print("View 'v_spatial_audio_readiness_audit' successfully recreated in BigQuery.")
except Exception as e:
    print(f"Error recreating view: {e}")

# Now, let's query the view to see if it has data
query_view_data = f"""
SELECT * FROM `driiiportfolio.meta_music.v_spatial_audio_readiness_audit` LIMIT 10
"""

try:
    df_view_data = pandas_gbq.read_gbq(query_view_data, project_id=BQ_PROJECT)
    if not df_view_data.empty:
        print("\nSUCCESS! View now contains data! Displaying first 10 rows:")
        display(df_view_data)
        print("The `v_spatial_audio_readiness_audit` view is now correctly populated and ready for use in Looker Studio.")
    else:
        print("\nThe view is *still* empty. This is unexpected. Please double check that both `dim_metadata_anomalies` AND `dim_music_catalog` were correctly uploaded/overwritten in BigQuery.")
except Exception as e:
    print(f"Error querying view: {e}")

"""## Summary of the Fix: Resolving the Empty `v_spatial_audio_readiness_audit` View

The `v_spatial_audio_readiness_audit` view initially returned no data in Looker Studio because of a referential integrity issue between the `dim_metadata_anomalies` and `dim_music_catalog` tables in BigQuery. Specifically, the `track_id` values associated with 'SPATIAL_VERSION_MISMATCH' anomalies in `dim_metadata_anomalies` did not have corresponding entries in `dim_music_catalog`.

**Root Cause Identified:**

1.  **Out-of-Sync Data:** The `dim_music_catalog` table in BigQuery was found to be out of sync with the local `dim_music_catalog.csv` file, which was used by the Python script to generate anomalies. This meant that even when `dim_metadata_anomalies` was correctly updated, the `JOIN` condition in the view failed because the necessary `track_id`s were missing from the BigQuery version of `dim_music_catalog`.

**Resolution Steps:**

1.  **Ensuring Referential Integrity for Anomalies:** A Python script (`y9LlWSaWbk3g`) was used to regenerate `dim_metadata_anomalies.csv`. This script explicitly linked anomalies to `track_id`s derived from the *local, up-to-date* `dim_music_catalog.csv`, guaranteeing that these anomaly `track_id`s would have a match if the `dim_music_catalog` was also up-to-date.
2.  **Updating `dim_metadata_anomalies` in BigQuery:** The newly generated `dim_metadata_anomalies.csv` was uploaded to `driiiportfolio.meta_music.dim_metadata_anomalies` in BigQuery, overwriting the existing table.
3.  **Synchronizing `dim_music_catalog` in BigQuery:** Crucially, the `dim_music_catalog` table in BigQuery also needed to be updated to match the local `dim_music_catalog.csv`. Once this final synchronization was completed, the `v_spatial_audio_readiness_audit` view was able to populate correctly, as both underlying tables now had consistent and matching `track_id`s.

### Required Project Updates

To prevent similar issues and ensure ongoing data integrity, the following updates are recommended:

1.  **`generator.py` Script Update:**
    *   The `generator.py` script (assumed to be responsible for generating raw or processed data files for the project) should be reviewed and updated to ensure that `dim_metadata_anomalies.csv` is consistently generated as part of its output, drawing directly from the most current `dim_music_catalog.csv`. This ensures that the local anomaly data always reflects the latest catalog.

2.  **SQL View (`v_spatial_audio_readiness_audit`) Update:**
    *   The SQL definition for `v_spatial_audio_readiness_audit` (as shown in cell `a39fd914`) remains correct. No changes are needed to the view's definition itself, as the issue was with the underlying data, not the view logic. The view will now function as expected given synchronized base tables.

3.  **Project Documentation Updates:**
    *   **`/content/data_dictionary.md`**: Review and update the data dictionary to include a comprehensive entry for `dim_metadata_anomalies`. This entry should detail its schema, purpose, and explicitly mention its foreign key relationship with `dim_music_catalog` via `track_id`.
    *   **`/content/README.md`**: Update the `README.md` to reflect the current data pipeline, explicitly mentioning the generation of `dim_metadata_anomalies.csv` and its reliance on an up-to-date `dim_music_catalog.csv`. Highlight the importance of maintaining synchronization between local CSV files and their BigQuery counterparts.
"""